name: Metrics-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-metrics-3d-contrib
    steps:
      - uses: actions/checkout@v1
      - uses: wizard503/wizard503@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}
          USERNAME: ${{ github.wizard503 }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
