name: Full-year calendar
uses: wizard503/wizard503@latest
with:
  filename: metrics.plugin.isocalendar.fullyear.svg
  token: ${{ secrets.TOKEN }}
  base: ""
  plugin_isocalendar: yes
  plugin_isocalendar_duration: full-year
